/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { ApiErrorItem } from './ApiErrorItem';
/**
 * Error payload based on RFC 7807 Problem Details.
 */
export type ApiErrorResponse = {
    /**
     * URI identifier that categorizes the error.
     */
    type?: string;
    /**
     * Short, human readable error title.
     */
    title: string;
    /**
     * HTTP status code generated by the originating server.
     */
    status: number;
    /**
     * Detailed explanation specific to this occurrence of the problem.
     */
    detail?: string;
    /**
     * URI reference that identifies the specific occurrence of the problem.
     */
    instance?: string;
    /**
     * Correlation identifier to help with support investigations.
     */
    traceId?: string;
    /**
     * Optional list with field level validation issues.
     */
    errors?: Array<ApiErrorItem>;
};

